
import pandas as pd
def label_count(df,family,label): return int(df[family].fillna('').astype(str).str.contains(label, regex=False).sum()) if family in df.columns else 0
def corpus_support(df,needed):
    counts={label:label_count(df,fam,label) for fam,label in needed}; present=sum(v>0 for v in counts.values()); repeated=sum(v>=3 for v in counts.values()); return min(5,max(1,present+(1 if repeated>=3 else 0))), counts
def gap_cards(df):
    cards=[
    {'title':'Process-aware NiTi martensite variant-mapping framework','status':'Future research extension, not a direct completed-work claim.','confidence':'Medium-high as an extension; not direct as an existing publication cluster.','needed':[('alloy_systems','NiTi shape memory alloys'),('mechanisms','martensitic transformations'),('methods','EBSD / TKD orientation microscopy'),('mechanisms','variant selection and texture'),('mechanisms','transformation matrices and symmetry'),('methods','additive manufacturing / LPBF process'),('properties','functional SMA response')],'logic':'The corpus strongly supports NiTi martensitic crystallography, EBSD/TKD variant analysis, and correspondence/matrix theory. It also contains LPBF/additive-manufacturing metallurgy in metallic alloys. The gap is to combine them into one process-aware framework linking LPBF thermal history to B2 parent grains, B19′ martensite variants, texture, and functional response.','research_questions':['Can LPBF thermal history bias B2 parent-grain texture in NiTi?','Does B2 parent texture control B19′ martensite variant selection?','Can EBSD/TKD reconstruct B2 parent grains from B19′ product orientations?','Are specific B19′ variant pairs favored near melt-pool boundaries or scan-vector directions?','Does variant distribution correlate with superelastic strain, hysteresis, or residual strain?','Can correspondence theory predict the observed B19′ variant families?','Does post-processing heat treatment preserve or erase LPBF-induced crystallographic memory?'],'data_needed':['LPBF parameters: power, scan speed, hatch spacing, layer thickness, scan strategy','Thermal descriptors: cooling-rate proxy, melt-pool geometry, thermal-gradient direction','EBSD/TKD maps: phase maps, IPF maps, grain maps, boundary maps, pole figures','Crystallographic descriptors: B2 parent orientations, B19′ product orientations, variant labels','Mechanical data: transformation stress, superelastic strain, hysteresis, residual strain','Heat-treatment data: annealing, aging, transformation temperatures'],'possible_outputs':['B2 parent-phase reconstruction map','B19′ martensite variant map','Variant-family census','Variant-pair misorientation histogram','Texture-memory map','Scan-vector versus variant-selection plot','Melt-pool boundary versus variant-distribution plot','Process → variant → superelasticity dashboard'],'risk_flags':['B19′ EBSD indexing can be difficult.','Parent reconstruction can be non-unique.','Variant assignment depends on the assumed orientation relationship.','LPBF residual stress and composition shifts can complicate interpretation.','Mechanical behavior depends on porosity, precipitates, texture, and residual stress, not only variants.']},
    {'title':'Weak-twin and unconventional-twin classifier from EBSD/TKD data','status':'Software/tooling extension grounded in repeated twin-crystallography themes.','confidence':'High as a tooling gap.','needed':[('mechanisms','twinning and weak twins'),('methods','EBSD / TKD orientation microscopy'),('mechanisms','transformation matrices and symmetry'),('alloy_systems','magnesium alloys'),('mechanisms','martensitic transformations')],'logic':'A classifier would detect type-I, type-II, compound, weak, axial weak, and unconventional twin candidates from orientation pairs.','research_questions':['Which misorientation pairs are classical twins and which are weak/unconventional?','Can EBSD/TKD data separate true twins from artefacts and variant boundaries?','How transferable are weak-twin descriptors between Mg, steels, and NiTi?'],'data_needed':['EBSD/TKD orientation tables','Phase symmetry','Candidate plane/direction sets','Misorientation tolerances','Manual expert labels for validation'],'possible_outputs':['Twin boundary probability map','Weak-twin candidate list','Axis-angle distribution','Twin-family confusion matrix','Expert-review report'],'risk_flags':['Orientation noise can mimic weak relations.','Plane-trace evidence may be needed.','Classification should not overrule crystallographic validation.']},
    {'title':'Parent-grain reconstruction for complex martensitic microstructures','status':'Implementation gap / practical engine.','confidence':'High as a direct extension of variant and orientation work.','needed':[('mechanisms','martensitic transformations'),('mechanisms','variant selection and texture'),('methods','EBSD / TKD orientation microscopy'),('alloy_systems','martensitic and bainitic steels'),('alloy_systems','NiTi shape memory alloys')],'logic':'A reusable parent-reconstruction engine would organize prior austenite/B2/β grains from product-phase orientation maps.','research_questions':['Which OR best reconstructs the parent phase?','Can packets/blocks/laths be assigned robustly?','How does parent texture propagate into product texture?'],'data_needed':['Product orientation maps','Candidate ORs','Phase symmetry definitions','Boundary graph','Tolerance calibration'],'possible_outputs':['Parent grain map','Packet/block/lath labels','OR-fit residual map','Variant census by parent grain'],'risk_flags':['Multiple ORs may fit.','Noisy boundaries can split parent grains.','Requires validation against retained parent phase if available.']},
    {'title':'Transformation-matrix library for metallurgy','status':'Core-code infrastructure gap.','confidence':'High as a crystallography-method gap.','needed':[('mechanisms','transformation matrices and symmetry'),('mechanisms','martensitic transformations'),('mechanisms','twinning and weak twins'),('methods','crystallographic modeling')],'logic':'A library would make distortion, orientation, and correspondence matrices executable for fcc→bcc/bct, B2→B19′, A1→L10, β→α/α′ and related transformations.','research_questions':['How should distortion, orientation, and correspondence matrices be represented consistently?','How are variants generated from parent symmetries?','Which twin operators appear between variants?'],'data_needed':['Lattice parameters','Symmetry operators','Orientation relationship matrices','Correspondence matrices'],'possible_outputs':['Variant list','Twin relation table','Misorientation matrix','Habit-plane candidates','Documentation notebooks'],'risk_flags':['A library must avoid hiding assumptions.','Different conventions can invert matrix meanings.']},
    {'title':'LPBF microstructure crystallography mapper','status':'Cross-theme future extension.','confidence':'Medium-high.','needed':[('methods','additive manufacturing / LPBF process'),('mechanisms','variant selection and texture'),('methods','EBSD / TKD orientation microscopy'),('mechanisms','recrystallization and grain evolution'),('mechanisms','martensitic transformations')],'logic':'Connect scan strategy and melt-pool geometry to texture, phase selection, recrystallization, and variants across Ti alloys, 316L, Cu-steel, red gold, and possibly NiTi.','research_questions':['How does beam shape alter texture and phase selection?','Can melt-pool geometry explain local variant or grain-boundary statistics?','Which post-treatments preserve AM texture?'],'data_needed':['AM parameters','Melt-pool images','EBSD/TKD maps','Thermal histories','Mechanical properties'],'possible_outputs':['Process-microstructure Sankey map','Melt-pool/texture overlay','AM heat-treatment comparison','Phase-stability dashboard'],'risk_flags':['AM datasets are heterogeneous.','Thermal history is often approximated.','Chemistry and porosity may dominate property links.']},
    {'title':'Precipitation-boundary interaction graph in Al-Mg-Si alloys','status':'Focused metallurgy data-model gap.','confidence':'Medium-high.','needed':[('alloy_systems','aluminum 6xxx and Al-Mg-Si-Cu'),('mechanisms','precipitation and ordering'),('methods','TEM / STEM / HRTEM'),('methods','EBSD / TKD orientation microscopy')],'logic':'A graph model could represent precipitate-particle-boundary interactions quantitatively.','research_questions':['Which boundaries nucleate or block β-Mg2Si-related precipitates?','How does temperature/interfacial energy sensitivity change the precipitation graph?','Can precipitate interaction motifs predict local mechanical response?'],'data_needed':['SEM/TEM precipitate detections','EBSD grain/boundary maps','Aging/temperature history','Composition'],'possible_outputs':['Precipitate-boundary network','Nucleation sensitivity map','Boundary interaction statistics'],'risk_flags':['Requires spatially registered microscopy.','Precipitate detection can be noisy.']},
    {'title':'Diffraction-artefact validator for claimed new phases','status':'Methodological quality-control extension.','confidence':'High.','needed':[('mechanisms','diffraction artefacts and phase identification'),('methods','TEM / STEM / HRTEM'),('methods','XRD and synchrotron diffraction'),('mechanisms','twinning and weak twins')],'logic':'Check whether extra spots or HRTEM patterns can arise from twinning, double diffraction, moiré, or stacking faults.','research_questions':['Can a claimed phase be reproduced by known artefact mechanisms?','Which twin/stacking-fault configurations generate the observed pattern?','What additional evidence is needed to confirm a new phase?'],'data_needed':['Diffraction spot coordinates','Candidate phases','Zone axis','Known parent/product symmetries','HRTEM/STEM images'],'possible_outputs':['Artefact probability report','Simulated diffraction comparison','Evidence checklist for phase claims'],'risk_flags':['Requires careful microscope geometry.','Cannot replace expert diffraction analysis.']},
    {'title':'Mg unconventional twinning classifier and strain-rate map','status':'Focused future analysis layer.','confidence':'Medium-high.','needed':[('alloy_systems','magnesium alloys'),('mechanisms','twinning and weak twins'),('methods','mechanical testing and deformation'),('methods','EBSD / TKD orientation microscopy')],'logic':'Map classical versus unconventional twinning as a function of strain rate, loading axis, and orientation.','research_questions':['How does strain rate change twinning mechanism?','Can unconventional twins be separated from simple-shear predictions?','Which orientation/loading combinations promote non-classical twins?'],'data_needed':['Micropillar orientations','Strain rate','Loading axis','EBSD maps','Twin labels'],'possible_outputs':['Twinning mechanism map','Strain-rate transition chart','Simple-shear mismatch score'],'risk_flags':['Small datasets may overfit.','Microscale results may not transfer to bulk alloys.']}
    ]
    for c in cards: c['coverage_score'], c['evidence_counts']=corpus_support(df,c['needed'])
    return cards
def theme_pair_matrix(df,col_a,col_b):
    rows=[]
    for _,row in df.iterrows():
        a=[x.strip() for x in str(row.get(col_a,'')).split(';') if x.strip()]; b=[x.strip() for x in str(row.get(col_b,'')).split(';') if x.strip()]
        for x in a:
            for y in b: rows.append((x,y,row.get('title','')))
    if not rows: return pd.DataFrame(columns=[col_a,col_b,'count'])
    tmp=pd.DataFrame(rows,columns=[col_a,col_b,'title']); return tmp.groupby([col_a,col_b]).size().reset_index(name='count').sort_values('count', ascending=False)
